### ISSUE TITLE
Build fail since commit 18dc85c5890852a596a5f5db9d3c813e98d2571b cause of missing GRMustacheContextStrategy reference

### ISSUE THREAD

**Issue by shouze** [groue/GRMustache#10]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_GRMustacheContextStrategy", referenced from:
      objc-class-ref in libGRMustache1-ios4.a(GRMustacheTemplate.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
